# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a7b606c362e9a81d99ec54c866e1051b19740afbe56a608915d6ed4e3f6c90b11e445a6bc4c73ccea3bc00ed16f7b30b421884ff6de88db73472969b3666a03c

test:
  secret_key_base: 1c0b72e6d5d486576f708fd0ef16fe6efca37bafc66d8e708d9f5780ec62af58350d7b7b23b2ce85cd0c931135bdae69cbc3c301dc8a431621a4b6ecf9abca37

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
